labels:
    type: xgboost-demo
    owner: dia-engop
    maintainer: herman
trainingInput:
    scaleTier: standard-1
    runtime_version: "2.1"
    pythonVersion: "3.7"
    scheduling:
      maxWaitTime: 3600s
      maxRunningTime: 7200s