labels:
    type: xgboost-demo
    owner: dia-engop
    maintainer: herman
trainingInput:
    scaleTier: CUSTOM
    workerCount: 2
    masterType: n1-standard-8
    workerType: n1-standard-4
    runtime_version: "2.1"
    pythonVersion: "3.7"
    scheduling:
      maxWaitTime: 3600s
      maxRunningTime: 7200s